name = "iLQGames"
uuid = "ae812560-bd7e-11e9-3bd3-b502f7cff3d3"
authors = ["lassepe <lasse.peters@tuhh.de>"]
version = "0.2.6"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IdentityRanges = "bbac6d45-d8f3-5730-bfe4-7a449cd117ca"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ORCA = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ColorSchemes = "3.9"
Colors = "0.12"
DataStructures = "0.17, 0.18"
DiffResults = "1.0"
DocStringExtensions = "0.8"
ForwardDiff = "0.10"
GR = "0.49, 0.50, 0.51, 0.52, 0.53, 0.54, 0.55, 0.57"
IdentityRanges = "0.3"
LaTeXStrings = "1.1"
ORCA = "0.3, 0.4, 0.5"
Parameters = "0.12"
Plots = "1.3"
Reexport = "0.2, 1.0"
StaticArrays = "1.0"
julia = "1"
